name: myauth
description: Offline Authenticator App
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # OTP generation
  otp: ^3.1.4

  # QR Scanner (stable version)
  mobile_scanner: ^3.5.7

  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Encryption
  encrypt: ^5.0.3
  crypto: ^3.0.3

  # QR display
  qr_flutter: ^4.1.0

  # Biometric authentication
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/myauth.png